const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const sql = fs.readFileSync(path.join(root,'supabase','migrations','20260919123614_public_access_and_multi_owner.sql'),'utf8');

assert.match(sql,/create table public\.public_capabilities/);
assert.match(sql,/grant execute on function public\.current_public_capabilities\(\) to anon, authenticated/);
assert.match(sql,/owner_set_public_capabilities/);
assert.match(sql,/revoke all on function public\.owner_set_public_capabilities\(jsonb\) from public, anon/);
assert.match(sql,/not public\.is_app_owner\(\)/);
assert.match(sql,/drop index if exists public\.app_admins_one_active_owner/);
assert.match(sql,/last_owner_cannot_be_removed/);
assert.match(sql,/next_role not in \('owner','co_admin','none'\)/);
assert.match(sql,/owner_auth_cutover_readiness/);
assert.match(sql,/i\.provider<>'google'/);
assert.match(sql,/auth\.uid\(\) is null and public\.has_public_capability\('member_content'\)/);
assert.match(sql,/grant execute on function public\.member_announcement_index\(integer,integer\),public\.member_announcement_detail\(text\) to anon, authenticated/);
const layer = fs.readFileSync(path.join(root,'docs','capability-layer.js'),'utf8');
const app = fs.readFileSync(path.join(root,'docs','app.js'),'utf8');
const html = fs.readFileSync(path.join(root,'docs','index.html'),'utf8');
const config = fs.readFileSync(path.join(root,'docs','account-config.js'),'utf8');
const runtime = fs.readFileSync(path.join(root,'supabase','tests','database','public_access_rls.test.sql'),'utf8');
assert.match(layer,/current_public_capabilities/);
assert.match(layer,/owner_set_public_capabilities/);
assert.match(layer,/owner_auth_cutover_readiness/);
assert.ok(html.indexOf('account-config.js') < html.indexOf('account-auth.js'));
assert.match(config,/document\.write\('<script src="capability-layer\.js/);
assert.match(config,/googleLoginUiEnabled: true/);
assert.match(app,/getPublicCapabilities/);
assert.match(app,/data-admin-role="owner"/);
assert.match(runtime,/co-admin cannot write PUBLIC capabilities/);
assert.match(runtime,/two active owners are supported/);
assert.match(runtime,/downgrade keeps one active owner/);
console.log('PUBLIC_ACCESS_CONTRACT_PASS');
