"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const migration = fs.readFileSync(path.join(root, "supabase/migrations/20260911183000_announcement_archive_reference.sql"), "utf8");
const app = fs.readFileSync(path.join(root, "docs/app.js"), "utf8");
const auth = fs.readFileSync(path.join(root, "docs/account-auth.js"), "utf8");
const index = fs.readFileSync(path.join(root, "docs/index.html"), "utf8");
assert.match(migration, /create table if not exists private\.announcement_archive/);
assert.match(migration, /create table if not exists private\.announcement_archive_attachments/);
assert.match(migration, /create table if not exists private\.announcement_reference_knowledge/);
assert.match(migration, /action in \('keep', 'archive'\)/);
assert.ok(migration.indexOf("insert into private.announcement_archive") < migration.indexOf("delete from private.announcement_member_content"), "archive write must precede ACTIVE removal");
assert.match(migration, /not exists \(select 1 from private\.announcement_lifecycle[\s\S]*action='archive'/);
assert.match(migration, /if actor is null or not public\.is_app_admin\(\)/);
assert.match(migration, /announcement_cleanup_review_history/);
assert.match(migration, /validity text not null default 'historical_reference'/);
assert.match(migration, /reference_value in \('HIGH', 'MEDIUM', 'LOW', 'NONE'\)/);
assert.match(index, /id="adminCleanupScan"[^>]*>檢查無效公告/);
assert.match(index, /id="adminArchiveToggle"[^>]*>歷史公告/);
assert.match(app, /getAdminCleanupDecisions/);
assert.match(app, /data-cleanup-action="keep"/);
assert.match(app, /data-cleanup-action="archive"/);
assert.match(app, /data-archive-restore/);
assert.match(auth, /admin_review_announcement_cleanup/);
assert.match(auth, /admin_list_archived_announcements/);
assert.match(auth, /admin_restore_archived_announcement/);
console.log("Announcement cleanup database contract passed");
