"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const migration = fs.readFileSync(path.join(root, "supabase/migrations/20260911160000_announcement_lifecycle_cleanup.sql"), "utf8");
const app = fs.readFileSync(path.join(root, "docs/app.js"), "utf8");
const auth = fs.readFileSync(path.join(root, "docs/account-auth.js"), "utf8");
const index = fs.readFileSync(path.join(root, "docs/index.html"), "utf8");
assert.match(migration, /create table if not exists private\.announcement_lifecycle/);
assert.match(migration, /action text not null check \(action in \('keep', 'delete'\)\)/);
assert.match(migration, /delete from private\.announcement_member_content/);
assert.match(migration, /not exists \([\s\S]*announcement_lifecycle[\s\S]*action = 'delete'/);
assert.match(migration, /if actor is null or not public\.is_app_admin\(\)/);
assert.match(migration, /announcement_cleanup_review_history/);
const tombstoneSchema = migration.slice(0, migration.indexOf("-- Deleted announcements are excluded"));
assert.doesNotMatch(tombstoneSchema, /detail jsonb|snippet text|summary text/);
assert.match(migration, /grant execute on function public\.announcement_deleted_ids\(\) to anon, authenticated, service_role/);
assert.match(index, /id="adminCleanupScan"[^>]*>檢查無效公告/);
assert.match(app, /getAdminCleanupDecisions/);
assert.match(app, /data-cleanup-action="keep"/);
assert.match(app, /data-cleanup-action="delete"/);
assert.match(auth, /admin_review_announcement_cleanup/);
console.log("Announcement cleanup database contract passed");
