"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const migration = fs.readFileSync(path.join(root, "supabase", "migrations", "20260903224000_admin_account_panel.sql"), "utf8");
const app = fs.readFileSync(path.join(root, "docs", "app.js"), "utf8");
const css = fs.readFileSync(path.join(root, "docs", "style.css"), "utf8");
assert.match(migration, /create or replace function public\.admin_list_account_access\(\)/);
assert.match(migration, /if not public\.is_app_admin\(\) then raise exception 'admin required'/);
assert.match(migration, /create trigger create_pending_account_access after insert on auth\.users/);
assert.match(migration, /admin_review_account\(uuid, text\) to authenticated/);
assert.match(migration, /cannot review own account/);
assert.match(migration, /revoke all on function public\.create_pending_account_access\(\) from public, anon, authenticated/);
assert.match(app, /移除使用權/);
assert.match(app, /window\.confirm/);
assert.match(app, /getAccountAccess/);
assert.match(app, /等待管理員核准後才能使用個人功能/);
assert.match(app, /isAdminAccount/);
assert.match(app, /tab === "admin" && !isAdminAccount\(\)/);
assert.match(css, /\.function-dock\[hidden\] \{ display: none !important; \}/);
console.log("Admin account-management security contract tests passed");
