const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const sql = fs.readFileSync(path.join(root,'supabase','migrations','20260919123614_public_access_and_multi_owner.sql'),'utf8');

assert.match(sql,/create table public\.public_capabilities/);
assert.match(sql,/grant execute on function public\.current_public_capabilities\(\) to anon, authenticated/);
assert.match(sql,/owner_set_public_capabilities/);
assert.match(sql,/revoke all on function public\.owner_set_public_capabilities\(jsonb\) from public, anon/);
assert.match(sql,/not public\.is_app_owner\(\)/);
assert.match(sql,/drop index if exists public\.app_admins_one_active_owner/);
assert.match(sql,/last_owner_cannot_be_removed/);
assert.match(sql,/next_role not in \('owner','co_admin','none'\)/);
assert.match(sql,/owner_auth_cutover_readiness/);
assert.match(sql,/i\.provider<>'google'/);
assert.match(sql,/auth\.uid\(\) is null and public\.has_public_capability\('member_content'\)/);
assert.match(sql,/grant execute on function public\.member_announcement_index\(integer,integer\),public\.member_announcement_detail\(text\) to anon, authenticated/);
const layer = fs.readFileSync(path.join(root,'docs','capability-layer.js'),'utf8');
const app = fs.readFileSync(path.join(root,'docs','app.js'),'utf8');
const html = fs.readFileSync(path.join(root,'docs','index.html'),'utf8');
const config = fs.readFileSync(path.join(root,'docs','account-config.js'),'utf8');
const runtime = fs.readFileSync(path.join(root,'supabase','tests','database','public_access_rls.test.sql'),'utf8');
const hardening = fs.readFileSync(path.join(root,'supabase','migrations','20260920121839_remove_public_notifications.sql'),'utf8');
const publicToday = fs.readFileSync(path.join(root,'supabase','migrations','20260926121500_public_today_and_pending_access.sql'),'utf8');
assert.match(layer,/current_public_capabilities/);
assert.match(layer,/owner_set_public_capabilities/);
assert.match(layer,/owner_auth_cutover_readiness/);
assert.match(layer,/PUBLIC_KEYS = \["member_content", "assistant", "timetable", "calendar", "today"\]/);
assert.doesNotMatch(layer,/PUBLIC_KEYS = \[[^\]]*notifications/);
assert.match(layer,/functionDock: approved \|\| publicEntry/);
assert.match(layer,/publicCurrent\[key\] === true \|\| approved && current\[key\] === true/);
assert.match(layer,/function canUseToday\(\) \{ return has\("today"\) \|\| anyPersonal\(\); \}/);
assert.match(layer,/setHidden\(button, false\)/);
assert.match(layer,/button\.disabled = !allowed/);
assert.match(layer,/tab === "latest" \|\| tab === "sub"/);
assert.match(layer,/if \(!owner\) \{\s*if \(existing\) existing\.remove\(\)/);
assert.doesNotMatch(layer,/if \(requirement === "personal"\) return anyPersonal\(\)/);
assert.doesNotMatch(layer,/if \(!approved\) return true/);
assert.match(app,/tab === "assistant" && capabilities\.has\("assistant"\)/);
assert.match(app,/tab === "timetable" && capabilities\.has\("timetable"\)/);
assert.match(app,/tab === "calendar" && capabilities\.has\("calendar"\)/);
assert.doesNotMatch(app,/tab !== "latest" && !hasSignedInAccount\(\)/);
assert.match(app,/LS_VISITOR_CONTEXT = "cyNews\.visitorContext\.v1"/);
assert.match(app,/state\.profile = saveVisitorContext\(profile\)/);
assert.match(app,/"已儲存在此裝置"/);
assert.match(hardening,/delete from public\.public_capabilities where capability = 'notifications'/);
assert.match(hardening,/capability in \('member_content','assistant','timetable','calendar'\)/);
assert.doesNotMatch(hardening,/array\['member_content','assistant','timetable','calendar','notifications'\]/);
assert.match(runtime,/PUBLIC can never receive personalized notifications/);
assert.match(runtime,/owner RPC cannot grant PUBLIC notifications/);
assert.ok(html.indexOf('account-config.js') < html.indexOf('account-auth.js'));
assert.match(config,/document\.write\('<script src="capability-layer\.js/);
assert.match(config,/googleLoginUiEnabled: true/);
assert.match(app,/getPublicCapabilities/);
assert.match(app,/data-admin-role="owner"/);
assert.match(runtime,/co-admin cannot write PUBLIC capabilities/);
assert.match(runtime,/two active owners are supported/);
assert.match(runtime,/downgrade keeps one active owner/);
assert.match(publicToday,/capability in \('member_content','assistant','timetable','calendar','today'\)/);
assert.match(publicToday,/values \('today', false\)/);
assert.match(publicToday,/array\['member_content','assistant','timetable','calendar','today'\]/);
assert.match(publicToday,/public\.has_public_capability\('member_content'\) or/);
console.log('PUBLIC_ACCESS_CONTRACT_PASS');
