"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const migration = fs.readFileSync(path.join(root, "supabase/migrations/20260905083758_account_roles_service_levels_and_email_outbox.sql"), "utf8");
const app = fs.readFileSync(path.join(root, "docs/app.js"), "utf8");
const auth = fs.readFileSync(path.join(root, "docs/account-auth.js"), "utf8");
const sync = fs.readFileSync(path.join(root, "docs/supabase-sync.js"), "utf8");
const index = fs.readFileSync(path.join(root, "docs/index.html"), "utf8");
const worker = fs.readFileSync(path.join(root, "supabase/functions/account-email-worker/index.ts"), "utf8");
const hardening = fs.readFileSync(path.join(root, "supabase/migrations/20260905085250_remove_legacy_admin_path_and_add_indexes.sql"), "utf8");
const scheduler = fs.readFileSync(path.join(root, "supabase/scheduler/activate_account_email_cron.sql"), "utf8");

assert.match(migration, /admin_role in \('owner', 'co_admin'\)/);
assert.match(migration, /function public\.is_app_owner\(\)/);
assert.match(migration, /if not public\.is_app_owner\(\) then/);
assert.match(migration, /next_role not in \('co_admin', 'none'\)/);
assert.match(migration, /administrator role must be removed first/);
assert.match(migration, /service_level in \('full', 'timetable_only'\)/);
assert.match(migration, /function public\.has_full_service_account\(\)/);
assert.match(migration, /approved_tasks_select[\s\S]*has_full_service_account/);
assert.match(migration, /function public\.request_account_access\(\)/);
assert.match(migration, /set status = 'pending', requested_at = now\(\)/);
assert.match(migration, /account_email_outbox/);
assert.match(migration, /revoke all on table private\.account_email_outbox from public, anon, authenticated/);
assert.match(migration, /grant execute on function public\.claim_account_email_outbox\(integer\) to service_role/);
assert.match(migration, /registration_notice/);
assert.match(migration, /access_reapplied/);
assert.match(hardening, /drop function public\.admin_review_account\(uuid, text\)/);
assert.match(hardening, /account_access_status_requested_idx/);
assert.match(hardening, /account_email_outbox_pending_idx/);

assert.match(auth, /admin_list_account_access/);
assert.match(auth, /admin_update_account/);
assert.match(auth, /owner_set_admin_role/);
assert.match(auth, /request_account_access/);
assert.match(sync, /serviceLevel === "timetable_only"/);
assert.match(sync, /feature unavailable for timetable-only account/);
assert.match(app, /function isTimetableOnly\(\)/);
assert.match(app, /此帳號目前只有課表服務/);
assert.match(app, /data-admin-access="approved"/);
assert.match(app, /data-admin-role="co_admin"/);
assert.match(index, /id="adminSearch"/);
assert.match(index, /id="adminStatusFilter"/);
assert.match(index, /id="adminRoleFilter"/);
assert.match(index, /id="adminServiceFilter"/);
assert.match(index, /id="viewTimetable"/);
assert.match(index, /id="accountReapply"/);
assert.match(worker, /x-account-email-worker-token/);
assert.match(worker, /idempotency-key/);
assert.match(worker, /RESEND_API_KEY/);
assert.doesNotMatch(worker, /re_[A-Za-z0-9_-]{12,}/, "no Resend secret is committed");
assert.match(scheduler, /account_email_worker_token/);
assert.match(scheduler, /cron\.schedule/);
assert.doesNotMatch(scheduler, /re_[A-Za-z0-9_-]{12,}/, "scheduler contains no provider secret");

console.log("Account role, service-level, re-application, and email-outbox contract tests passed");
