"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const child = require("node:child_process");

const root = path.resolve(__dirname, "..");
child.execFileSync(process.execPath, [path.join(root, "tools", "build-staging.js")], { cwd: root, stdio: "pipe" });
const production = fs.readFileSync(path.join(root, "docs", "index.html"), "utf8");
const staging = fs.readFileSync(path.join(root, "dist-staging", "index.html"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "dist-staging", "manifest-staging.webmanifest"), "utf8"));
const harness = fs.readFileSync(path.join(root, "dist-staging", "acceptance-user-tasks.js"), "utf8");
const sw = fs.readFileSync(path.join(root, "dist-staging", "sw.js"), "utf8");
const revision = (staging.match(/(?:style\.css|app\.js)\?v=(staging-[a-f0-9]{12})/) || [])[1];
const config = fs.readFileSync(path.join(root, "docs", "account-config.js"), "utf8");
const behavioral = fs.readFileSync(path.join(root, "tests", "test_rls_behavioral.js"), "utf8");

assert(!production.includes("acceptance-user-tasks.js"), "production source must not load the acceptance harness");
assert(!production.includes("cynews-staging-banner"), "production source must not contain a staging banner");
assert(staging.includes('name="robots" content="noindex,nofollow,noarchive"'));
assert(staging.includes("STAGING／測試環境・非正式站"));
assert(revision, "staging build must create a single content-derived shell revision");
assert(!staging.includes("?v=25"), "staging cannot retain production shell query versions");
assert(staging.includes('src="acceptance-user-tasks.js?v=' + revision + '"'));
assert(staging.includes('src="app.js?v=' + revision + '"'));
assert.equal(manifest.name, "嘉校快訊 Staging／測試版");
assert.equal(fs.readFileSync(path.join(root, "dist-staging", "robots.txt"), "utf8"), "User-agent: *\nDisallow: /\n");
assert(harness.includes('params.get("acceptance") !== "user-tasks" && !localStorage.getItem(STORAGE)'), "harness is query gated and survives the exact-root OAuth callback");
assert(harness.includes('localStorage.setItem(STORAGE'), "interrupted OAuth acceptance can resume from a new staging tab");
assert(!harness.includes('sessionStorage.setItem(STORAGE'), "acceptance progress cannot disappear with the OAuth-return tab");
assert(harness.includes("location.origin !== expected"), "harness is exact-origin gated");
assert(harness.includes("adapter ownership guard failed"));
assert(harness.includes("cross-user read isolation failed"));
assert(harness.includes("account outbox isolation failed"));
assert(harness.includes("created_at: spoofedAt"), "raw spoof fixture must satisfy schema timestamps before RLS evaluation");
assert(harness.includes('spoof.data.code !== "42501"'), "raw spoof acceptance must require an RLS-specific rejection");
assert(harness.includes("raw ownership spoof was not rejected by RLS"));
assert(harness.includes("created_at: now"), "outbox fixture must satisfy user_tasks timestamps");
assert(harness.includes('new URL("/acceptance-companion.html", location.origin)'), "USER_A companion must use the lifecycle-free staging page");
assert(harness.includes("cleanupReservedOutbox"), "acceptance recovery must remove only reserved outbox fixtures");
assert(harness.includes("BLOCKED：\" + (area.status.dataset.step"), "blocked reports must identify a sanitized acceptance stage");
assert(!harness.includes("service_role"));
assert(sw.includes('var CACHE = "cy-news-' + revision + '";'), "staging cache namespace is distinct and advances with shell changes");
assert(sw.includes('"./manifest-staging.webmanifest"'));
assert(sw.includes('"./staging.css?v=' + revision + '"'));
assert(sw.includes('"./acceptance-user-tasks.js?v=' + revision + '"'));
assert(sw.includes('"./acceptance-companion.html?v=' + revision + '"'));
assert(sw.includes('if (req.mode === "navigate")'), "staging navigation must prefer fresh HTML over a stale app shell");
const companion = fs.readFileSync(path.join(root, "dist-staging", "acceptance-companion.html"), "utf8");
assert(companion.includes('acceptance-user-tasks.js?v=' + revision));
assert(companion.includes('account-auth.js?v=' + revision));
assert(!companion.includes("app.js"), "companion must not initialize the production account lifecycle");
assert(!companion.includes("account-sync.js"), "companion must not drain any account outbox");
assert(sw.includes('url.searchParams.has("code")'), "OAuth callback navigation remains uncacheable");
assert(config.includes("allowedRedirectUrls"));
assert(config.includes("https://cy-school-news-staging.vercel.app/"));
assert(!behavioral.includes("passed for A=${a}"), "behavioral test output must not reveal user UUIDs");
assert(behavioral.includes("passed for USER_A and USER_B"));
console.log("Staging build and sanitized acceptance harness tests passed");
