const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const migrations = path.join(__dirname, "..", "supabase", "migrations");
const foundation = fs.readFileSync(path.join(migrations, "003_reminder_push_foundation.sql"), "utf8");
const hardeningName = fs.readdirSync(migrations).find((name) => name.endsWith("_reminder_delivery_hardening.sql"));
assert.ok(hardeningName, "official CLI-generated reminder hardening migration is required");
const hardening = fs.readFileSync(path.join(migrations, hardeningName), "utf8");
const workerName = fs.readdirSync(migrations).find((name) => name.endsWith("_reminder_worker_rpc.sql"));
assert.ok(workerName, "official CLI-generated reminder worker migration is required");
const worker = fs.readFileSync(path.join(migrations, workerName), "utf8");
const sql = foundation + "\n" + hardening;
for (const table of ["user_reminder_rules", "user_push_subscriptions", "reminder_jobs", "reminder_deliveries"]) {
  assert.match(sql, new RegExp("create table if not exists public\\." + table));
  assert.match(sql, new RegExp("alter table public\\." + table + " enable row level security"));
}
assert.match(sql, /using \(\(select auth\.uid\(\)\) = user_id\)/);
assert.match(sql, /with check \(\(select auth\.uid\(\)\) = user_id\)/);
assert.match(sql, /-- Jobs and deliveries are server-worker tables/);
assert.match(hardening, /create table if not exists public\.reminder_targets/);
assert.match(hardening, /create schema if not exists private/);
assert.match(hardening, /create or replace function private\.validate_reminder_rule_target/);
assert.doesNotMatch(hardening, /security definer[\s\S]{0,160}public\.validate_reminder_rule_target/);
assert.match(hardening, /grant execute on function public\.valid_reminder_offsets\(integer\[\]\) to authenticated/);
assert.match(hardening, /Publication dates are not valid targets/);
assert.match(hardening, /target_kind = 'manual' and manual_target_at is not null/);
assert.match(hardening, /raise exception 'unverified reminder target'/);
assert.match(hardening, /foreign key \(rule_id, user_id\)/);
assert.match(hardening, /foreign key \(job_id, user_id\)/);
assert.match(hardening, /foreign key \(push_subscription_id, user_id\)/);
assert.match(hardening, /unique \(endpoint\)/);
assert.match(hardening, /attempts integer not null default 0/);
assert.match(hardening, /lease_until timestamptz/);
assert.match(hardening, /next_attempt_at timestamptz/);
assert.match(hardening, /status in \('pending', 'processing', 'sent', 'skipped', 'retry', 'dead', 'cancelled'\)/);
assert.match(hardening, /revoke all on table public\.reminder_jobs from anon, authenticated/);
assert.match(hardening, /revoke all on table public\.reminder_deliveries from anon, authenticated/);
assert.match(hardening, /grant select, insert, update on table public\.user_reminder_rules to authenticated/);
assert.match(hardening, /grant select, insert, update on table public\.user_push_subscriptions to authenticated/);
assert.match(hardening, /date-only targets resolve at local midnight/);
assert.match(worker, /security invoker/);
assert.doesNotMatch(worker, /security definer/);
assert.match(worker, /for update of d skip locked/);
assert.match(worker, /on conflict \(job_id, push_subscription_id\) do nothing/);
assert.match(worker, /schedule_baseline_at/);
assert.match(worker, /on conflict \(rule_id, offset_days, target_at\) do nothing/);
assert.match(worker, /d\.lease_token = delivery_lease_token/);
assert.match(worker, /d\.lease_until >= now\(\)/);
assert.match(worker, /grant execute on function public\.claim_reminder_deliveries\(integer, integer\) to service_role/);
assert.match(worker, /revoke all on function public\.claim_reminder_deliveries\(integer, integer\) from public, anon, authenticated/);
assert.match(worker, /outcome not in \('sent', 'invalid', 'retry', 'dead'\)/);
assert.match(worker, /effective_outcome = 'invalid'/);
assert.match(worker, /invalidated_at = coalesce\(invalidated_at, now\(\)\)/);
assert.match(worker, /d\.attempts >= j\.max_attempts/);
console.log("Reminder schema security contract tests passed");

