"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const index = fs.readFileSync(path.join(root, "docs", "index.html"), "utf8");
const style = fs.readFileSync(path.join(root, "docs", "style.css"), "utf8");
const app = fs.readFileSync(path.join(root, "docs", "app.js"), "utf8");

assert.match(index, /立即檢查更新/, "refresh control uses truthful wording across staging and production");
assert.match(index, /id="refreshState"[^>]*role="status"[^>]*aria-live="polite"/, "refresh progress is announced accessibly");
assert.match(app, /正在取得雲端已發布資料/);
assert.match(app, /同步完成；雲端尚未發布新版本/);
assert.match(app, /目前顯示離線快取，未取得雲端新資料/);
assert.match(style, /--sans: var\(--serif\)/, "one readable serif family is used across the interface");
assert.match(style, /#btnRefresh\.is-refreshing svg/);
assert.match(style, /@media \(prefers-reduced-motion: reduce\)/, "motion preference remains respected");
assert.ok((style.match(/@media \(prefers-color-scheme: dark\)/g) || []).length >= 2,
  "the final editorial palette preserves a readable dark variant");
assert.match(index, /Noto\+Serif\+TC:wght@400;500;700;900/, "the complete readable font family is loaded");
assert.match(index, /style\.css\?v=46/);
assert.match(index, /search-taxonomy\.js\?v=52/, "search taxonomy loads before the query parser");
assert.match(index, /search-query\.js\?v=52/, "semantic search terms load before the application");
assert.match(index, /search-query\.js\?v=52[\s\S]*announcement-validity-reviewed\.js\?v=52[\s\S]*announcement-validity\.js\?v=52[\s\S]*assistant-qa\.js\?v=53/, "reviewed validity loads before answers");
const appVersion = index.match(/src="app\.js\?v=(\d+)"/);
assert.ok(appVersion, "application script has a numeric cache version");
const serviceWorker = fs.readFileSync(path.join(root, "docs", "sw.js"), "utf8");
assert.ok(serviceWorker.includes("./app.js?v=" + appVersion[1] + '"'),
  "the HTML and Service Worker cache refer to the same application version");
assert.match(index, /id="appLoading"[^>]*role="status"/, "initial data loading is announced accessibly");
assert.match(style, /\.app-loading/, "initial data loading has a dedicated view");
assert.doesNotMatch(style, /--calligraphy:/, "the interface does not mix a second display font into reading UI");
assert.match(app, /finishInitialLoading/, "the loading view closes after initial data work");
assert.doesNotMatch(index, /不會猜/, "assistant copy is direct rather than defensive");
assert.match(app, /資料說明/, "assistant keeps limitations available without interrupting the answer");
assert.match(app, /官方來源（/, "assistant answers use a source panel template");
assert.match(app, /為什麼這樣回答/, "assistant evidence is available without interrupting the answer");
assert.match(app, /searchTimer = setTimeout[\s\S]*200\);/, "full-corpus ranking is debounced while the user types");
assert.match(index, /id="navMenuToggle"[^>]*aria-expanded="false"[^>]*aria-controls="navMenu"/, "mobile navigation is exposed through one accessible menu button");
assert.match(index, /id="navMenu"[^>]*hidden/, "function menu starts closed");
assert.match(index, /id="navCurrentLabel">選單</);
assert.match(index, /id="viewHome"[^>]*aria-labelledby="homeTitle"/);
assert.match(index, /id="homeTitle"[^>]*class="calligraphy-title"[^>]*>.*學校公告.*匯集系統/s);
assert.ok((index.match(/data-home-tab=/g) || []).length >= 5);
assert.match(index, /id="taskComposerToggle"[^>]*aria-expanded="false"/);
assert.match(index, /id="taskForm"[^>]*hidden/);
assert.match(index, /class="my-card/);
assert.match(style, /\.calligraphy-title/);
assert.match(style, /\.task-composer\[hidden\]/);
assert.match(index, /id="nicknameSchool"[^>]*required/, "first-login onboarding asks for the preferred school");
assert.match(index, /id="profileSchool" required/, "account settings require an explicit school");
assert.match(index, /id="assistantScope"/, "school assistant exposes an explicit cross-school search scope");
assert.match(app, /mentionedSchool\(question\)/, "a school named in the question overrides the default scope");
assert.match(app, /applyPreferredSchool\(state\.profile\.school_id/, "the account school becomes the default data shard");
assert.match(style, /\.function-dock/, "single-button function menu has a dedicated responsive layout");
assert.match(index, /id="todayTimetable"/, "today view includes a class timetable region");
assert.match(index, /我的班級（查看課表需要）/, "profile explains when a class is needed");
assert.match(app, /data\/class-timetables\.json/, "today view loads the generated public timetable data");
assert.match(app, /officialTimetableUrl/, "timetable source links are constrained to the official school origin");
assert.match(style, /\.timetable-week/, "weekly timetable has a dedicated responsive layout");

console.log("Editorial UI and honest refresh status contract tests passed");
