# -*- coding: utf-8 -*-
"""Build a lightweight, deterministic manifest of trusted future targets.

The manifest is generated by GitHub Actions. It never promotes announcement
publication dates and never accepts unprovenanced calendar/body dates.
"""
from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent.parent
TW = timezone(timedelta(hours=8))
ALLOWED_ANNOUNCEMENT = {
    ("deadline", "verified_announcement_deadline"): "announcement_deadline",
    ("event", "verified_announcement_event"): "announcement_event",
}


def _https(value):
    parsed = urlparse(str(value or ""))
    return str(value) if parsed.scheme == "https" and parsed.netloc else ""


def _target_at(date):
    try:
        return datetime.strptime(str(date), "%Y-%m-%d").replace(tzinfo=TW).isoformat()
    except ValueError:
        return ""


def build_targets(announcements, calendars, *, today=None):
    today = today or datetime.now(TW).date().isoformat()
    targets = []
    seen = set()
    for item in announcements or []:
        for index, event in enumerate(item.get("calendar_events") or []):
            target_kind = ALLOWED_ANNOUNCEMENT.get((event.get("kind"), event.get("provenance")))
            date = str(event.get("date") or "")
            source_url = _https(item.get("url"))
            revision = str(event.get("source_revision") or item.get("detail_revision") or "")
            if not target_kind or date < today or not _target_at(date) or not source_url or not revision:
                continue
            target_id = f"announcement:{item.get('id')}:{event.get('kind')}:{index}"
            key = (target_kind, target_id, revision)
            if key in seen:
                continue
            seen.add(key)
            targets.append({
                "target_kind": target_kind, "target_id": target_id,
                "target_at": _target_at(date), "title": str(item.get("title") or event.get("title") or "公告").strip(),
                "source_url": source_url, "provenance": "official_announcement",
                "source_revision": revision,
            })
    for event in calendars or []:
        date = str(event.get("start_date") or event.get("date") or "")
        source_url = _https(event.get("source_url"))
        revision = str(event.get("source_revision") or "")
        if event.get("provenance") != "official_school_calendar" or date < today or not _target_at(date) or not source_url or not revision:
            continue
        target_id = "calendar:" + str(event.get("id") or "")
        key = ("official_calendar_event", target_id, revision)
        if not event.get("id") or key in seen:
            continue
        seen.add(key)
        targets.append({
            "target_kind": "official_calendar_event", "target_id": target_id,
            "target_at": _target_at(date), "title": str(event.get("title") or "校曆活動").strip(),
            "source_url": source_url, "provenance": "official_calendar",
            "source_revision": revision,
        })
    return sorted(targets, key=lambda row: (row["target_at"], row["target_kind"], row["target_id"]))


def _items(path):
    if not path.exists():
        return []
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        return value.get("items", []) if isinstance(value, dict) else value
    except (OSError, ValueError):
        return []


def main():
    announcements = _items(ROOT / "docs/data/announcements.json") + _items(ROOT / "docs/data/archive.json")
    calendars = _items(ROOT / "docs/data/calendar-events.json")
    output = ROOT / "docs/data/reminder-targets.json"
    output.write_text(json.dumps({
        "schema_version": 1,
        "targets": build_targets(announcements, calendars),
    }, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"[info] reminder target manifest → {output}")


if __name__ == "__main__":
    main()
