-- Scalable account administration with explicit owner/co-admin boundaries,
-- service levels, re-application, and a server-only email delivery outbox.

alter table public.app_admins
  add column if not exists admin_role text not null default 'co_admin'
  check (admin_role in ('owner', 'co_admin'));

update public.app_admins
set admin_role = 'owner'
where user_id = (
  select user_id from public.app_admins
  where revoked_at is null
  order by created_at asc, user_id asc
  limit 1
)
and not exists (
  select 1 from public.app_admins where admin_role = 'owner' and revoked_at is null
);

create unique index if not exists app_admins_one_active_owner
  on public.app_admins ((admin_role))
  where admin_role = 'owner' and revoked_at is null;

alter table public.account_access
  add column if not exists service_level text not null default 'full'
  check (service_level in ('full', 'timetable_only')),
  add column if not exists last_reapplied_at timestamptz;

alter table public.admin_audit_log
  drop constraint if exists admin_audit_log_action_check;
alter table public.admin_audit_log
  add constraint admin_audit_log_action_check check (action in (
    'invite_requested', 'account_approved', 'account_rejected',
    'access_reapplied', 'service_changed', 'coadmin_granted', 'coadmin_revoked'
  ));

create table if not exists private.account_email_outbox (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  recipient_email text not null,
  template text not null check (template in (
    'registration_notice', 'access_approved', 'access_rejected',
    'access_reapplied', 'service_changed', 'coadmin_granted', 'coadmin_revoked'
  )),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  claimed_at timestamptz,
  sent_at timestamptz,
  attempts integer not null default 0,
  last_error text
);

revoke all on table private.account_email_outbox from public, anon, authenticated;

create or replace function private.queue_account_email(
  event_key text,
  recipient_email text,
  template text,
  payload jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, private
as $$
begin
  if event_key is null or length(event_key) > 180 then
    raise exception 'invalid email event key' using errcode = '22023';
  end if;
  if recipient_email is null or length(recipient_email) > 254 then
    raise exception 'invalid email recipient' using errcode = '22023';
  end if;
  insert into private.account_email_outbox (event_key, recipient_email, template, payload)
  values (event_key, lower(recipient_email), template, coalesce(payload, '{}'::jsonb))
  on conflict (event_key) do nothing;
end;
$$;

revoke all on function private.queue_account_email(text, text, text, jsonb) from public, anon, authenticated;

create or replace function public.is_app_owner()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select exists (
    select 1 from public.app_admins
    where user_id = auth.uid() and admin_role = 'owner' and revoked_at is null
  )
$$;

revoke all on function public.is_app_owner() from public, anon;
grant execute on function public.is_app_owner() to authenticated;

drop function if exists public.current_account_access();
create function public.current_account_access()
returns table(status text, is_admin boolean, admin_role text, service_level text, can_reapply boolean)
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
begin
  if auth.uid() is null then
    raise exception 'authenticated user required' using errcode = '28000';
  end if;
  return query
    select
      coalesce(access.status, 'pending')::text,
      (admin.user_id is not null),
      admin.admin_role::text,
      coalesce(access.service_level, 'full')::text,
      (coalesce(access.status, 'pending') = 'rejected')
    from (select 1) seed
    left join public.account_access access on access.user_id = auth.uid()
    left join public.app_admins admin on admin.user_id = auth.uid() and admin.revoked_at is null;
end;
$$;

revoke all on function public.current_account_access() from public, anon;
grant execute on function public.current_account_access() to authenticated;

drop function if exists public.admin_list_account_access();
create function public.admin_list_account_access(
  search_text text default '',
  status_filter text default 'all',
  role_filter text default 'all',
  service_filter text default 'all',
  page_size integer default 50,
  page_offset integer default 0
)
returns table(
  user_id uuid,
  email text,
  status text,
  service_level text,
  admin_role text,
  requested_at timestamptz,
  reviewed_at timestamptz,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = pg_catalog, auth, public
as $$
declare
  normalized_search text := lower(trim(coalesce(search_text, '')));
  safe_limit integer := least(greatest(coalesce(page_size, 50), 1), 100);
  safe_offset integer := greatest(coalesce(page_offset, 0), 0);
begin
  if not public.is_app_admin() then
    raise exception 'admin required' using errcode = '42501';
  end if;
  if status_filter not in ('all', 'pending', 'approved', 'rejected')
    or role_filter not in ('all', 'owner', 'co_admin', 'member')
    or service_filter not in ('all', 'full', 'timetable_only') then
    raise exception 'invalid account filter' using errcode = '22023';
  end if;

  return query
  with filtered as (
    select
      access.user_id,
      users.email::text as email,
      access.status::text as status,
      access.service_level::text as service_level,
      admin.admin_role::text as admin_role,
      access.requested_at,
      access.reviewed_at
    from public.account_access access
    join auth.users users on users.id = access.user_id
    left join public.app_admins admin on admin.user_id = access.user_id and admin.revoked_at is null
    where (normalized_search = '' or lower(users.email::text) like '%' || normalized_search || '%')
      and (status_filter = 'all' or access.status = status_filter)
      and (service_filter = 'all' or access.service_level = service_filter)
      and (role_filter = 'all'
        or (role_filter = 'member' and admin.user_id is null)
        or admin.admin_role = role_filter)
  )
  select filtered.*, count(*) over ()
  from filtered
  order by
    case filtered.status when 'pending' then 0 when 'approved' then 1 else 2 end,
    filtered.requested_at desc,
    filtered.user_id
  limit safe_limit offset safe_offset;
end;
$$;

revoke all on function public.admin_list_account_access(text, text, text, text, integer, integer) from public, anon;
grant execute on function public.admin_list_account_access(text, text, text, text, integer, integer) to authenticated;

create or replace function public.admin_update_account(
  target_user_id uuid,
  next_status text,
  next_service_level text
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, auth, public, private
as $$
declare
  actor uuid := auth.uid();
  target_email text;
  previous_service text;
begin
  if not public.is_app_admin() then
    raise exception 'admin required' using errcode = '42501';
  end if;
  if target_user_id is null or target_user_id = actor then
    raise exception 'cannot review own account' using errcode = '22023';
  end if;
  if exists (select 1 from public.app_admins where user_id = target_user_id and revoked_at is null) then
    raise exception 'administrator role must be removed first' using errcode = '42501';
  end if;
  if next_status not in ('approved', 'rejected')
    or next_service_level not in ('full', 'timetable_only') then
    raise exception 'invalid access update' using errcode = '22023';
  end if;

  select users.email::text, access.service_level
    into target_email, previous_service
  from auth.users users
  join public.account_access access on access.user_id = users.id
  where users.id = target_user_id;
  if target_email is null then
    raise exception 'account not found' using errcode = 'P0002';
  end if;

  update public.account_access
  set status = next_status,
      service_level = next_service_level,
      reviewed_at = now(),
      reviewed_by = actor
  where user_id = target_user_id;

  insert into public.admin_audit_log (actor_id, action, target_user_id, target_email)
  values (actor,
    case
      when next_status = 'approved' and previous_service is distinct from next_service_level then 'service_changed'
      when next_status = 'approved' then 'account_approved'
      else 'account_rejected'
    end,
    target_user_id,
    target_email
  );

  perform private.queue_account_email(
    'access:' || target_user_id::text || ':' || txid_current()::text,
    target_email,
    case
      when next_status = 'rejected' then 'access_rejected'
      when previous_service is distinct from next_service_level then 'service_changed'
      else 'access_approved'
    end,
    jsonb_build_object('service_level', next_service_level)
  );
end;
$$;

revoke all on function public.admin_update_account(uuid, text, text) from public, anon;
grant execute on function public.admin_update_account(uuid, text, text) to authenticated;

create or replace function public.owner_set_admin_role(target_user_id uuid, next_role text)
returns void
language plpgsql
security definer
set search_path = pg_catalog, auth, public, private
as $$
declare
  actor uuid := auth.uid();
  target_email text;
begin
  if not public.is_app_owner() then
    raise exception 'owner required' using errcode = '42501';
  end if;
  if target_user_id is null or target_user_id = actor then
    raise exception 'cannot change own owner role' using errcode = '22023';
  end if;
  if next_role not in ('co_admin', 'none') then
    raise exception 'invalid administrator role' using errcode = '22023';
  end if;

  select users.email::text into target_email from auth.users users where users.id = target_user_id;
  if target_email is null then
    raise exception 'account not found' using errcode = 'P0002';
  end if;

  if next_role = 'co_admin' then
    if not exists (
      select 1 from public.account_access
      where user_id = target_user_id and status = 'approved'
    ) then
      raise exception 'account must be approved first' using errcode = '22023';
    end if;
    insert into public.app_admins (user_id, admin_role, created_by, revoked_at)
    values (target_user_id, 'co_admin', actor, null)
    on conflict (user_id) do update
      set admin_role = 'co_admin', created_by = actor, revoked_at = null;
    update public.account_access set service_level = 'full' where user_id = target_user_id;
  else
    update public.app_admins
    set revoked_at = now()
    where user_id = target_user_id and admin_role = 'co_admin' and revoked_at is null;
    if not found then
      raise exception 'active co-admin not found' using errcode = 'P0002';
    end if;
  end if;

  insert into public.admin_audit_log (actor_id, action, target_user_id, target_email)
  values (actor, case when next_role = 'co_admin' then 'coadmin_granted' else 'coadmin_revoked' end, target_user_id, target_email);
  perform private.queue_account_email(
    'admin-role:' || target_user_id::text || ':' || txid_current()::text,
    target_email,
    case when next_role = 'co_admin' then 'coadmin_granted' else 'coadmin_revoked' end,
    '{}'::jsonb
  );
end;
$$;

revoke all on function public.owner_set_admin_role(uuid, text) from public, anon;
grant execute on function public.owner_set_admin_role(uuid, text) to authenticated;

create or replace function public.request_account_access()
returns text
language plpgsql
security definer
set search_path = pg_catalog, auth, public, private
as $$
declare
  actor uuid := auth.uid();
  actor_email text;
  current_status text;
  event_id text;
  admin_row record;
begin
  if actor is null then
    raise exception 'authenticated user required' using errcode = '28000';
  end if;
  select users.email::text, access.status
    into actor_email, current_status
  from auth.users users
  left join public.account_access access on access.user_id = users.id
  where users.id = actor;

  if current_status = 'approved' then return 'approved'; end if;
  if current_status = 'pending' then return 'pending'; end if;

  insert into public.account_access (user_id, status, requested_at, last_reapplied_at)
  values (actor, 'pending', now(), now())
  on conflict (user_id) do update
    set status = 'pending', requested_at = now(), last_reapplied_at = now(), reviewed_at = null, reviewed_by = null;

  insert into public.admin_audit_log (actor_id, action, target_user_id, target_email)
  values (actor, 'access_reapplied', actor, actor_email);

  event_id := 'reapply:' || actor::text || ':' || txid_current()::text;
  for admin_row in
    select users.email::text as email
    from public.app_admins admin
    join auth.users users on users.id = admin.user_id
    where admin.revoked_at is null and users.email is not null
  loop
    perform private.queue_account_email(event_id || ':' || md5(admin_row.email), admin_row.email, 'access_reapplied', jsonb_build_object('applicant_email', actor_email));
  end loop;
  return 'pending';
end;
$$;

revoke all on function public.request_account_access() from public, anon;
grant execute on function public.request_account_access() to authenticated;

create or replace function public.create_pending_account_access()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, auth, public, private
as $$
declare admin_row record;
begin
  insert into public.account_access (user_id, status)
  values (new.id, 'pending')
  on conflict (user_id) do nothing;
  for admin_row in
    select users.email::text as email
    from public.app_admins admin
    join auth.users users on users.id = admin.user_id
    where admin.revoked_at is null and users.email is not null
  loop
    perform private.queue_account_email(
      'registration:' || new.id::text || ':' || md5(admin_row.email),
      admin_row.email,
      'registration_notice',
      jsonb_build_object('applicant_email', new.email)
    );
  end loop;
  return new;
end;
$$;

revoke all on function public.create_pending_account_access() from public, anon, authenticated;

create or replace function public.has_full_service_account()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select exists (
    select 1 from public.account_access
    where user_id = auth.uid() and status = 'approved' and service_level = 'full'
  )
$$;

revoke all on function public.has_full_service_account() from public, anon;
grant execute on function public.has_full_service_account() to authenticated;

-- Timetable-only accounts may keep their own preferences (school/class), but
-- cannot use subscriptions, read state, tasks, reminders, or push devices.
drop policy if exists approved_subscriptions_select on public.user_subscriptions;
drop policy if exists approved_subscriptions_insert on public.user_subscriptions;
drop policy if exists approved_subscriptions_update on public.user_subscriptions;
drop policy if exists approved_subscriptions_delete on public.user_subscriptions;
create policy approved_subscriptions_select on public.user_subscriptions for select to authenticated using ((select auth.uid()) = user_id and (select public.has_full_service_account()));
create policy approved_subscriptions_insert on public.user_subscriptions for insert to authenticated with check ((select auth.uid()) = user_id and (select public.has_full_service_account()));
create policy approved_subscriptions_update on public.user_subscriptions for update to authenticated using ((select auth.uid()) = user_id and (select public.has_full_service_account())) with check ((select auth.uid()) = user_id and (select public.has_full_service_account()));
create policy approved_subscriptions_delete on public.user_subscriptions for delete to authenticated using ((select auth.uid()) = user_id and (select public.has_full_service_account()));

drop policy if exists approved_reads_select on public.user_reads;
drop policy if exists approved_reads_insert on public.user_reads;
drop policy if exists approved_reads_update on public.user_reads;
drop policy if exists approved_reads_delete on public.user_reads;
create policy approved_reads_select on public.user_reads for select to authenticated using ((select auth.uid()) = user_id and (select public.has_full_service_account()));
create policy approved_reads_insert on public.user_reads for insert to authenticated with check ((select auth.uid()) = user_id and (select public.has_full_service_account()));
create policy approved_reads_update on public.user_reads for update to authenticated using ((select auth.uid()) = user_id and (select public.has_full_service_account())) with check ((select auth.uid()) = user_id and (select public.has_full_service_account()));
create policy approved_reads_delete on public.user_reads for delete to authenticated using ((select auth.uid()) = user_id and (select public.has_full_service_account()));

drop policy if exists approved_tasks_select on public.user_tasks;
drop policy if exists approved_tasks_insert on public.user_tasks;
drop policy if exists approved_tasks_update on public.user_tasks;
drop policy if exists approved_tasks_delete on public.user_tasks;
create policy approved_tasks_select on public.user_tasks for select to authenticated using ((select auth.uid()) = user_id and (select public.has_full_service_account()));
create policy approved_tasks_insert on public.user_tasks for insert to authenticated with check ((select auth.uid()) = user_id and (select public.has_full_service_account()));
create policy approved_tasks_update on public.user_tasks for update to authenticated using ((select auth.uid()) = user_id and (select public.has_full_service_account())) with check ((select auth.uid()) = user_id and (select public.has_full_service_account()));
create policy approved_tasks_delete on public.user_tasks for delete to authenticated using ((select auth.uid()) = user_id and (select public.has_full_service_account()));

drop policy if exists approved_reminder_rules_select on public.user_reminder_rules;
drop policy if exists approved_reminder_rules_insert on public.user_reminder_rules;
drop policy if exists approved_reminder_rules_update on public.user_reminder_rules;
create policy approved_reminder_rules_select on public.user_reminder_rules for select to authenticated using ((select auth.uid()) = user_id and (select public.has_full_service_account()));
create policy approved_reminder_rules_insert on public.user_reminder_rules for insert to authenticated with check ((select auth.uid()) = user_id and (select public.has_full_service_account()));
create policy approved_reminder_rules_update on public.user_reminder_rules for update to authenticated using ((select auth.uid()) = user_id and (select public.has_full_service_account())) with check ((select auth.uid()) = user_id and (select public.has_full_service_account()));

drop policy if exists approved_push_subscriptions_select on public.user_push_subscriptions;
drop policy if exists approved_push_subscriptions_insert on public.user_push_subscriptions;
drop policy if exists approved_push_subscriptions_update on public.user_push_subscriptions;
create policy approved_push_subscriptions_select on public.user_push_subscriptions for select to authenticated using ((select auth.uid()) = user_id and (select public.has_full_service_account()));
create policy approved_push_subscriptions_insert on public.user_push_subscriptions for insert to authenticated with check ((select auth.uid()) = user_id and (select public.has_full_service_account()));
create policy approved_push_subscriptions_update on public.user_push_subscriptions for update to authenticated using ((select auth.uid()) = user_id and (select public.has_full_service_account())) with check ((select auth.uid()) = user_id and (select public.has_full_service_account()));

-- Service-role-only queue API used by the email Edge Function.
create or replace function public.claim_account_email_outbox(batch_size integer default 20)
returns table(id bigint, recipient_email text, template text, payload jsonb)
language plpgsql
security definer
set search_path = pg_catalog, private
as $$
begin
  return query
  with claimed as (
    select outbox.id
    from private.account_email_outbox outbox
    where outbox.sent_at is null
      and outbox.attempts < 5
      and (outbox.claimed_at is null or outbox.claimed_at < now() - interval '10 minutes')
    order by outbox.created_at asc
    limit least(greatest(coalesce(batch_size, 20), 1), 50)
    for update skip locked
  )
  update private.account_email_outbox outbox
  set claimed_at = now(), attempts = attempts + 1
  from claimed
  where outbox.id = claimed.id
  returning outbox.id, outbox.recipient_email, outbox.template, outbox.payload;
end;
$$;

create or replace function public.finish_account_email_outbox(message_id bigint, delivered boolean, failure text default null)
returns void
language plpgsql
security definer
set search_path = pg_catalog, private
as $$
begin
  update private.account_email_outbox
  set sent_at = case when delivered then now() else sent_at end,
      claimed_at = null,
      last_error = case when delivered then null else left(coalesce(failure, 'delivery failed'), 500) end
  where id = message_id;
end;
$$;

revoke all on function public.claim_account_email_outbox(integer) from public, anon, authenticated;
revoke all on function public.finish_account_email_outbox(bigint, boolean, text) from public, anon, authenticated;
grant execute on function public.claim_account_email_outbox(integer) to service_role;
grant execute on function public.finish_account_email_outbox(bigint, boolean, text) to service_role;
