-- Administrator-only account review. Browser clients never receive an admin key.
create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  revoked_at timestamptz
);

create table if not exists public.account_access (
  user_id uuid primary key references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  requested_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete restrict,
  action text not null check (action in ('invite_requested', 'account_approved', 'account_rejected')),
  target_user_id uuid references auth.users(id) on delete set null,
  target_email text,
  created_at timestamptz not null default now()
);

alter table public.app_admins enable row level security;
alter table public.account_access enable row level security;
alter table public.admin_audit_log enable row level security;
revoke all on public.app_admins, public.account_access, public.admin_audit_log from anon, authenticated;

create or replace function public.is_app_admin()
returns boolean language sql stable security definer
set search_path = pg_catalog, public
as $$ select exists (select 1 from public.app_admins where user_id = auth.uid() and revoked_at is null) $$;

create or replace function public.current_account_access()
returns table(status text, is_admin boolean)
language plpgsql stable security definer
set search_path = pg_catalog, auth, public
as $$
begin
  if auth.uid() is null then raise exception 'authenticated user required' using errcode = '28000'; end if;
  return query select coalesce((select aa.status from public.account_access aa where aa.user_id = auth.uid()), 'pending'), public.is_app_admin();
end;
$$;

create or replace function public.admin_list_account_access()
returns table(user_id uuid, email text, status text, requested_at timestamptz, reviewed_at timestamptz)
language plpgsql stable security definer
set search_path = pg_catalog, auth, public
as $$
begin
  if not public.is_app_admin() then raise exception 'admin required' using errcode = '42501'; end if;
  return query select aa.user_id, u.email, aa.status, aa.requested_at, aa.reviewed_at
    from public.account_access aa join auth.users u on u.id = aa.user_id
    order by case aa.status when 'pending' then 0 else 1 end, aa.requested_at asc;
end;
$$;

create or replace function public.admin_review_account(target_user_id uuid, next_status text)
returns void language plpgsql security definer
set search_path = pg_catalog, auth, public
as $$
declare actor uuid := auth.uid(); target_email text;
begin
  if not public.is_app_admin() then raise exception 'admin required' using errcode = '42501'; end if;
  if target_user_id is null or target_user_id = actor then raise exception 'cannot review own account' using errcode = '22023'; end if;
  if next_status not in ('approved', 'rejected') then raise exception 'invalid access status' using errcode = '22023'; end if;
  select email into target_email from auth.users where id = target_user_id;
  if target_email is null then raise exception 'account not found' using errcode = 'P0002'; end if;
  insert into public.account_access (user_id, status, reviewed_at, reviewed_by)
  values (target_user_id, next_status, now(), actor)
  on conflict (user_id) do update set status = excluded.status, reviewed_at = excluded.reviewed_at, reviewed_by = excluded.reviewed_by;
  insert into public.admin_audit_log (actor_id, action, target_user_id, target_email)
  values (actor, case when next_status = 'approved' then 'account_approved' else 'account_rejected' end, target_user_id, target_email);
end;
$$;

create or replace function public.create_pending_account_access()
returns trigger language plpgsql security definer
set search_path = pg_catalog, public
as $$
begin
  insert into public.account_access (user_id, status) values (new.id, 'pending') on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists create_pending_account_access on auth.users;
create trigger create_pending_account_access after insert on auth.users
for each row execute function public.create_pending_account_access();

revoke all on function public.is_app_admin() from public, anon;
revoke all on function public.current_account_access() from public, anon;
revoke all on function public.admin_list_account_access() from public, anon;
revoke all on function public.admin_review_account(uuid, text) from public, anon;
revoke all on function public.create_pending_account_access() from public, anon, authenticated;
grant execute on function public.is_app_admin(), public.current_account_access(), public.admin_list_account_access(), public.admin_review_account(uuid, text) to authenticated;
